### PR TITLE
Update abpindo_specific_hide.txt

### PR DESCRIPTION
**Pull request by 3xploiton3**
Menghilangkan kolom iklan di web tokopedia

### CODE REVIEW

**Comment by gmarcher** [comment]
Tokoped dan sejenisnya termasuk kategori self promotion, dan tidak seharusnya masuk di filter, kecuali menjadi filter pribadi. User yang membuka situs jual-beli sudah pasti karena akan melihat iklan, jadi tidak wajar jika dibuat filter khusus situs jual beli. mohon pengertiannya
Mungkin tidak pernah saya tulis secara langsung, namun ABPindo memiliki kebijakan sama dengan [easylist](https://easylist.to/pages/policy.html)

**Comment by 3xploiton3** [comment]
easylist juga menghapus sponsor/ads pihak ke 3

contoh
https://www.amazon.com/s?k=i7+9700k&crid=32Z2X7JQ8AAX7&sprefix=i7+%2Caps%2C437&ref=nb_sb_ss_i_1_3

https://i.imgur.com/lwDAYck.png

**Comment by gmarcher** [comment]
Itu karena masuk General element hiding rules, jadi target utamanya bukan amazon. 
atau seperti `||amazon-adsystem.com^$third-party` pernah tampil di situs lain, maka akan difilter, tapi pada khasus ini tokopedia tidak punya situs iklan sendiri (misal: ad.tokoped.com) untuk melayani iklan diluar situs toped.

**Comment by saiqulhaq-hh** [comment]
klo kayak gini masuk gak?
image

**Comment by gmarcher** [comment]
apakah iklannya muncul di luar tokopedia?

> klo kayak gini masuk gak? image

**Comment by partingscientist** [comment]
According to [EasyList policy](https://easylist.to/pages/policy.html):

> Self-promotion (any type of advertising that **promotes goods or services that are owned or operated by the domain owner and doesn’t get commercially compensated for by third parties** (examples can include new features, new posts, newsletters, subscriptions to printed media products, merchandise etc.)) won't be targeted directly.

One can argue that Tokopedia ads are operated by Tokopedia itself, but Tokopedia is definitely compensated by a third party to show those ads, that is the product sellers themselves. As an example consistent to this, EasyList addressed [Amazon's sponsored products](https://github.com/easylist/easylist/blob/2ecd766e111a0db72d5acd1462b89b92f51db3d4/easylist/easylist_specific_hide_abp.txt#L45) and [BestBuy's promoted products](https://github.com/easylist/easylist/blob/2ecd766e111a0db72d5acd1462b89b92f51db3d4/easylist/easylist_specific_hide_abp.txt#L109-L112), both of which are seller-paid programs [[1]](https://advertising.amazon.com/solutions/products/sponsored-products)[[2]](https://www.ebay.com/help/selling/listings/listing-tips/promoted-listings?id=4164).

I hope this decision can be reconsidered.

**Pull request closed without merging**
